// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/mikerjacobi/in-touch-server/design
// --out=$(GOPATH)/src/github.com/mikerjacobi/in-touch-server
// --version=v1.1.0-dirty
//
// API "adder": Application Media Types
//
// The content of this file is auto-generated, DO NOT MODIFY

package client

import (
	"github.com/goadesign/goa"
	"net/http"
	"unicode/utf8"
)

// Login media type (default view)
//
// Identifier: application/vnd.login+json; view=default
type Login struct {
	Password *string `form:"password,omitempty" json:"password,omitempty" xml:"password,omitempty"`
	Username *string `form:"username,omitempty" json:"username,omitempty" xml:"username,omitempty"`
}

// Validate validates the Login media type instance.
func (mt *Login) Validate() (err error) {
	if mt.Password != nil {
		if utf8.RuneCountInString(*mt.Password) < 6 {
			err = goa.MergeErrors(err, goa.InvalidLengthError(`response.password`, *mt.Password, utf8.RuneCountInString(*mt.Password), 6, true))
		}
	}
	if mt.Username != nil {
		if utf8.RuneCountInString(*mt.Username) < 1 {
			err = goa.MergeErrors(err, goa.InvalidLengthError(`response.username`, *mt.Username, utf8.RuneCountInString(*mt.Username), 1, true))
		}
	}
	return
}

// DecodeLogin decodes the Login instance encoded in resp body.
func (c *Client) DecodeLogin(resp *http.Response) (*Login, error) {
	var decoded Login
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}
