version: 0.1

environment_variables:
  plaintext:
    env: "prod"
            
phases:
  install:
    commands:
      - echo "installing..."
      - apt-get update
      - apt-get --assume-yes install software-properties-common
      - add-apt-repository ppa:ubuntu-lxc/lxd-stable
      - apt-get update
      - apt-get --assume-yes install golang
  pre_build:
    commands:
      - echo "prebuilding..."
      - eval `aws ecr get-login --region us-east-1`
  build:
    commands:
      - echo "building..."
      - cd server && go build
      - docker build -t 532898105683.dkr.ecr.us-east-1.amazonaws.com/in-touch-server:latest server
  post_build:
    commands:
      - echo "post building..."
      - docker push 532898105683.dkr.ecr.us-east-1.amazonaws.com/in-touch-server:latest
artifacts:
  files:
    - "**/*"
  discard-paths: no
