// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/mikerjacobi/in-touch-server/design
// --out=$(GOPATH)/src/github.com/mikerjacobi/in-touch-server
// --version=v1.1.0-dirty
//
// API "adder": Application User Types
//
// The content of this file is auto-generated, DO NOT MODIFY

package app
